[package]
name = "Marketplace"
version = "0.0.0"

[addresses]
marketplace = "_"

[dependencies]
AptosFramework = { local = "../../framework/aptos-framework" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-token", rev = "mainnet" }
AptosTokenObjects = { local = "../../framework/aptos-token-objects" }