

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.AxiomEliminationRoadmap
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.AxiomEliminationRoadmap
