

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.AxiomEliminationComplete
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.AxiomEliminationComplete
