import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.Instr
import MovementFormal.MoveModel.Step
import MovementFormal.Experimental.ConfidentialAsset.Registration.BytecodeTranscriptionLemmas
import MovementFormal.Experimental.ConfidentialAsset.Registration.InstructionEffectCatalog

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.BytecodeSemanticsCatalog
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.BytecodeSemanticsCatalog
