import MovementFormal.MoveModel.Step
import MovementFormal.MoveModel.Programs.Registration
import MovementFormal.Experimental.ConfidentialAsset.Registration.VerifyMath
import MovementFormal.Experimental.ConfidentialAsset.Registration.TranscriptAlignment

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.BytecodeSmoke
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.BytecodeSmoke
