

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.BytecodeSemanticsComplete
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.BytecodeSemanticsComplete
