import MovementFormal.Experimental.ConfidentialAsset.Registration.BytecodeDifftestEval
import MovementFormal.MoveModel.Programs.RegistrationDifftestOracle
import MovementFormal.Experimental.ConfidentialAsset.Registration.Operational

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.BytecodeDifftestBridge
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.BytecodeDifftestBridge
