

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.BytecodeTranscriptionComplete
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.BytecodeTranscriptionComplete
