import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Step
import MovementFormal.Experimental.ConfidentialAsset.Registration.PCBoundaryConditions
import MovementFormal.Experimental.ConfidentialAsset.Registration.ExecutionTraceProperties

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.CompleteSingletonBranchProof
theorem stub : True := trivial
end MovementFormal.Experimental.ConfidentialAsset.Registration.CompleteSingletonBranchProof
