import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Step
import MovementFormal.Experimental.ConfidentialAsset.Registration.PCBoundaryConditions
import MovementFormal.Experimental.ConfidentialAsset.Registration.ExecutionTraceProperties

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.CompleteSingletonBranchProof
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.CompleteSingletonBranchProof
