

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.CompleteInvariantSystem
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.CompleteInvariantSystem
