

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.ConcreteWitnessBuilders
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.ConcreteWitnessBuilders
