

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.ConcretePCStepTemplates
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.ConcretePCStepTemplates
