

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.ConcreteValueFlowAnalysis
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.ConcreteValueFlowAnalysis
