import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Step
import MovementFormal.MoveModel.StepLemmas.Bundled
import MovementFormal.Experimental.ConfidentialAsset.Registration.ConcreteExecutionLemmas

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.ConcreteLemmaInstantiations
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.ConcreteLemmaInstantiations
