import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Step
import MovementFormal.MoveModel.StepLemmas.Basic
import MovementFormal.MoveModel.StepLemmas.Locals

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.ConcreteExecutionLemmas
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.ConcreteExecutionLemmas
