import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Step
import MovementFormal.Experimental.ConfidentialAsset.Registration.ContainerStoreProperties
import MovementFormal.Experimental.ConfidentialAsset.Registration.PCBoundaryConditions

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.ContainerStoreMonotonicity
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.ContainerStoreMonotonicity
