

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.CryptographicValueTracking
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.CryptographicValueTracking
