import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Step
import MovementFormal.Experimental.ConfidentialAsset.Registration.BytecodeTranscriptionLemmas
import MovementFormal.Experimental.ConfidentialAsset.Registration.PCBoundaryConditions

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.ErrorPathCompleteness
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.ErrorPathCompleteness
