

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.ErrorPathAnalysisComplete
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.ErrorPathAnalysisComplete
