import MovementFormal.Experimental.ConfidentialAsset.Registration.FunctionalSim
import MovementFormal.MoveModel.ExecResultDropMs
import MovementFormal.MoveModel.Programs.Registration

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.EvalEquiv
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.EvalEquiv
