import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Step
import MovementFormal.Experimental.ConfidentialAsset.Registration.FuelManagement
import MovementFormal.Experimental.ConfidentialAsset.Registration.ValidationLemmas

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.ExecutionTraceProperties
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.ExecutionTraceProperties
