import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Step
import MovementFormal.Experimental.ConfidentialAsset.Registration.ExecutionTraceProperties
import MovementFormal.Experimental.ConfidentialAsset.Registration.PCBoundaryConditions

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.ExecutionTracesDetailed
theorem stub : True := trivial
end MovementFormal.Experimental.ConfidentialAsset.Registration.ExecutionTracesDetailed
