

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.FinalIntegrationFramework
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.FinalIntegrationFramework
