import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Programs.Registration

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.FrameConstructionHelpers
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.FrameConstructionHelpers
