import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Step
import MovementFormal.Experimental.ConfidentialAsset.Registration.InvariantMaintenance
import MovementFormal.Experimental.ConfidentialAsset.Registration.FrameWellFormedness

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.GlobalStateInvariants
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.GlobalStateInvariants
