import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Step
import MovementFormal.Experimental.ConfidentialAsset.Registration.InvariantMaintenance
import MovementFormal.Experimental.ConfidentialAsset.Registration.FrameWellFormedness

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.GlobalStateInvariants
theorem stub : True := trivial
end MovementFormal.Experimental.ConfidentialAsset.Registration.GlobalStateInvariants
