

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.InstructionEncodingVerification
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.InstructionEncodingVerification
