import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Step
import MovementFormal.MoveModel.Instr

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.InstructionSemantics
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.InstructionSemantics
