import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.Experimental.ConfidentialAsset.Registration.PCBoundaryConditions
import MovementFormal.Experimental.ConfidentialAsset.Registration.ValidationLemmas

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.IntermediateStateProperties
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.IntermediateStateProperties
