import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.LocalsManagementLemmas
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.LocalsManagementLemmas
