import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Step
import MovementFormal.Experimental.ConfidentialAsset.Registration.RefIdManagementLemmas
import MovementFormal.Experimental.ConfidentialAsset.Registration.InvariantMaintenance

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.MemorySafetyProperties
theorem stub : True := trivial
end MovementFormal.Experimental.ConfidentialAsset.Registration.MemorySafetyProperties
