import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Step
import MovementFormal.Experimental.ConfidentialAsset.Registration.RefIdManagementLemmas
import MovementFormal.Experimental.ConfidentialAsset.Registration.InvariantMaintenance

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.MemorySafetyProperties
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.MemorySafetyProperties
