import MovementFormal.Experimental.ConfidentialAsset.Registration.VerifyMath
import MovementFormal.AptosStd.Crypto.Ristretto255

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.Operational
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.Operational
