import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Native.Registration
import MovementFormal.Experimental.ConfidentialAsset.Registration.ValidationLemmas

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.OracleSemantics
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.OracleSemantics
