import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Native.Registration
import MovementFormal.Experimental.ConfidentialAsset.Registration.OracleSemantics

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.OracleCorrespondenceProofs
theorem stub : True := trivial
end MovementFormal.Experimental.ConfidentialAsset.Registration.OracleCorrespondenceProofs
