

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.OracleInteractionPatterns
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.OracleInteractionPatterns
