import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.Native.Registration

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.OracleCallSpecifications
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.OracleCallSpecifications
