

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.PC11_20_Implementations
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.PC11_20_Implementations
