

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.PC20_30_Implementations
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.PC20_30_Implementations
