

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.PC31_43_Implementations
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.PC31_43_Implementations
