import MovementFormal.MoveModel.Programs.Registration

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.PC4_20_SimpleFacts
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.PC4_20_SimpleFacts
