import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.Experimental.ConfidentialAsset.Registration.FrameConstructionHelpers
import MovementFormal.Experimental.ConfidentialAsset.Registration.ValidationLemmas
import MovementFormal.Experimental.ConfidentialAsset.Registration.ErrorPathHandling

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.PCBoundaryConditions
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.PCBoundaryConditions
