import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Step
import MovementFormal.MoveModel.StepLemmas.Run
import MovementFormal.Experimental.ConfidentialAsset.Registration.FuelManagement

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.PCRangeComposition
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.PCRangeComposition
