import MovementFormal.Experimental.ConfidentialAsset.Registration.EvalEquiv
import MovementFormal.Experimental.ConfidentialAsset.Registration.Refinement

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.Phase6Composition
theorem stub : True := trivial
end MovementFormal.Experimental.ConfidentialAsset.Registration.Phase6Composition
