

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.PhaseSpecificInvariants
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.PhaseSpecificInvariants
