

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.PhaseCompositionImplementations
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.PhaseCompositionImplementations
