

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.Phase3SchnorrComputation
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.Phase3SchnorrComputation
