

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.PhaseBoundaryVerification
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.PhaseBoundaryVerification
