import MovementFormal.Experimental.ConfidentialAsset.Registration.EvalEquiv
import MovementFormal.Experimental.ConfidentialAsset.Registration.Refinement

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.Phase6Composition
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.Phase6Composition
