

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.ProofValidationFramework
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.ProofValidationFramework
