

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.ProofCompositionComplete
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.ProofCompositionComplete
