import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Step
import MovementFormal.Experimental.ConfidentialAsset.Registration.RefIdManagementLemmas
import MovementFormal.Experimental.ConfidentialAsset.Registration.ContainerStoreMonotonicity
import MovementFormal.Experimental.ConfidentialAsset.Registration.PCBoundaryConditions

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.ReferenceLifetimeAnalysis
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.ReferenceLifetimeAnalysis
