

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.ReferenceSafetyComplete
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.ReferenceSafetyComplete
