import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.Experimental.ConfidentialAsset.Registration.ContainerStoreProperties

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.RefIdManagementLemmas
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.RefIdManagementLemmas
