import MovementFormal.Experimental.ConfidentialAsset.Registration.FunctionalSim
import MovementFormal.Experimental.ConfidentialAsset.Registration.Refinement

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.RegisterEntryStub
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.RegisterEntryStub
