

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.SchnorrProtocolVerification
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.SchnorrProtocolVerification
