

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.SingletonBranchImplementation
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.SingletonBranchImplementation
