

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.SingletonBranchComplete
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.SingletonBranchComplete
