import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Step

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.StackManagementLemmas
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.StackManagementLemmas
