import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Step
import MovementFormal.Experimental.ConfidentialAsset.Registration.StackManagementLemmas
import MovementFormal.Experimental.ConfidentialAsset.Registration.StateTransitionLemmas

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.StackInvariantPreservation
theorem stub : True := trivial
end MovementFormal.Experimental.ConfidentialAsset.Registration.StackInvariantPreservation
