

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.StackManipulationComplete
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.StackManipulationComplete
