import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Step
import MovementFormal.Experimental.ConfidentialAsset.Registration.StackInvariantPreservation
import MovementFormal.Experimental.ConfidentialAsset.Registration.PCBoundaryConditions

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.StackDepthAnalysis
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.StackDepthAnalysis
