import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Step
import MovementFormal.Experimental.ConfidentialAsset.Registration.ValueTypePreservation
import MovementFormal.Experimental.ConfidentialAsset.Registration.PCBoundaryConditions

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.TypeCorrectnessProofs
theorem stub : True := trivial
end MovementFormal.Experimental.ConfidentialAsset.Registration.TypeCorrectnessProofs
