import MovementFormal.MoveModel.Value
import MovementFormal.Experimental.ConfidentialAsset.Registration.ValidationLemmas

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.ValidationLemmasRefined
theorem stub : True := trivial
end MovementFormal.Experimental.ConfidentialAsset.Registration.ValidationLemmasRefined
