import MovementFormal.MoveModel.Value
import MovementFormal.Experimental.ConfidentialAsset.Registration.ValidationLemmas

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.ValidationLemmasRefined
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.ValidationLemmasRefined
