import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Step
import MovementFormal.MoveModel.Native.Registration

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.ValidationLemmas
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.ValidationLemmas
