

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.ValueValidationComplete
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.ValueValidationComplete
