import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.State
import MovementFormal.MoveModel.Step
import MovementFormal.Experimental.ConfidentialAsset.Registration.ValidationLemmas

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.ValueTypePreservation
theorem stub : True := trivial
end MovementFormal.Experimental.ConfidentialAsset.Registration.ValueTypePreservation
