

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.ValueProvenanceTracking
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.ValueProvenanceTracking
