

namespace MovementFormal.Experimental.ConfidentialAsset.Registration.VerificationStatusSummary
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Registration.VerificationStatusSummary
