/-
Copyright (c) Move Industries.

Executable **`CryptoOracleWithBoolEq`** for the fixed VM trace
`0x1::difftest_registration_helpers::registration_roundtrip_vm`
(`chain_id=9`, `@0x1`/`@0x2`/`@0x3`, dk=42, k=9999).

Wire bytes are generated by:

`cargo run -p move-lean-difftest --bin print-difftest-registration-wire`

The carrier `Fin 8` is a **table oracle**: only the `pointMul` / `pointAdd` / `decompress` paths exercised
by `Operational.execVerifyRegistrationProof` on this trace are populated; everything else maps to a
sink state. This is **not** a general Ristretto model — it is a sound way to run `execVerifyRegistrationProof`
in `lake exe difftest` for this one oracle row (see `STUB_POLICY.md`).
-/

import AptosFormal.Experimental.ConfidentialAsset.Registration.Operational
import AptosFormal.Experimental.ConfidentialAsset.Registration.TranscriptAlignment
import AptosFormal.Experimental.ConfidentialAsset.Registration.VerifyMath
import AptosFormal.Move.Value
import Mathlib.Tactic.FinCases

open AptosFormal.Move
open AptosFormal.Experimental.ConfidentialAsset.Registration.Formal
open AptosFormal.Experimental.ConfidentialAsset.Registration.Operational
open AptosFormal.AptosStd.Crypto.Ristretto255
open RegistrationTranscriptAlignment
open RegistrationVerify

namespace AptosFormal.Move.Programs.RegistrationDifftestOracle

abbrev DifftestWirePt : Type := Fin 8

/-- Sink / wrong-branch token. -/
def ptBad : DifftestWirePt := ⟨7, by decide⟩

def ptH : DifftestWirePt := ⟨0, by decide⟩
def ptRhs : DifftestWirePt := ⟨1, by decide⟩
def ptEk : DifftestWirePt := ⟨2, by decide⟩
def ptMulHs : DifftestWirePt := ⟨3, by decide⟩
def ptMulEek : DifftestWirePt := ⟨4, by decide⟩

/-- `print-difftest-registration-wire` → `ek_bytes_hex`. -/
def difftestRegEkBytes : ByteArray :=
  ByteArray.mk #[
    166, 105, 246, 130, 61, 48, 217, 70, 117, 78, 136, 118, 239, 145, 118, 242,
    104, 118, 83, 176, 52, 109, 234, 2, 109, 19, 71, 241, 151, 86, 172, 77
  ]

/-- `print-difftest-registration-wire` → `commitment_bytes_hex`. -/
def difftestRegCommitmentBytes : ByteArray :=
  ByteArray.mk #[
    178, 104, 37, 61, 34, 169, 102, 130, 104, 9, 78, 17, 179, 101, 239, 224,
    83, 20, 179, 191, 85, 232, 246, 129, 208, 167, 97, 36, 197, 43, 23, 116
  ]

/-- `print-difftest-registration-wire` → `response_scalar_bytes_hex` (32-byte scalar encoding). -/
def difftestRegResponseBytes : ByteArray :=
  ByteArray.mk #[
    34, 212, 81, 110, 48, 73, 236, 104, 246, 40, 69, 83, 11, 209, 226, 161,
    218, 0, 212, 201, 196, 232, 2, 22, 166, 106, 81, 152, 241, 191, 129, 10
  ]

/-- Public inputs for the VM roundtrip (BCS addresses reuse `TranscriptAlignment`). -/
def difftestRegistrationRoundtripInputs : RegistrationFiatShamirInputs where
  chainId := 9
  senderBcs := bcsAddress0x1
  contractBcs := bcsAddress0x2
  tokenBcs := bcsAddress0x3
  ekBytes := difftestRegEkBytes
  commitmentRBytes := difftestRegCommitmentBytes

def difftestRegS : RistrettoScalar :=
  (scalarReducedFrom32Bytes difftestRegResponseBytes).get
    (by native_decide : (scalarReducedFrom32Bytes difftestRegResponseBytes).isSome)

def difftestRegE : RistrettoScalar :=
  (registrationChallengeScalarMove (registrationFiatShamirMsg difftestRegistrationRoundtripInputs)).get
    (by native_decide :
      (registrationChallengeScalarMove (registrationFiatShamirMsg difftestRegistrationRoundtripInputs)).isSome)

private def pointMulDifftest (p : DifftestWirePt) (s : RistrettoScalar) : DifftestWirePt :=
  if _ : p = ptH then
    if _ : s = difftestRegS then ptMulHs else ptBad
  else if _ : p = ptEk then
    if _ : s = difftestRegE then ptMulEek else ptBad
  else ptBad

private def pointAddDifftest (a b : DifftestWirePt) : DifftestWirePt :=
  if _ : a = ptMulHs then
    if _ : b = ptMulEek then ptRhs else ptBad
  else ptBad

private def pointDecompressDifftest (c : CompressedRistretto32) : Option DifftestWirePt :=
  if c.bytes = difftestRegCommitmentBytes then some ptRhs else none

private def pubkeyToPointDifftest (c : CompressedRistretto32) : Option DifftestWirePt :=
  if c.bytes = difftestRegEkBytes then some ptEk else none

private def difftestOracleCore : CryptoOracle DifftestWirePt where
  scalarFromBytes := scalarReducedFrom32Bytes
  challengeScalarFromMsg := registrationChallengeScalarMove
  hashToPointBase := ptH
  pointMul := pointMulDifftest
  pointAdd := pointAddDifftest
  pointEq := (· = ·)
  pointDecompress := pointDecompressDifftest
  pubkeyToPoint := pubkeyToPointDifftest

private theorem fin8_beq_iff : ∀ a b : DifftestWirePt, (a == b) = true ↔ a = b := by
  intro a b
  fin_cases a <;> fin_cases b <;> constructor <;> intro h <;> simp_all

/-- Table oracle for the VM-only registration roundtrip row. -/
def difftestRegistrationOracle : CryptoOracleWithBoolEq DifftestWirePt where
  toCryptoOracle := difftestOracleCore
  pointEqBool a b := a == b
  pointEq_bool_iff := fin8_beq_iff

theorem difftest_registration_exec_ok :
    execVerifyRegistrationProof difftestRegistrationOracle difftestRegistrationRoundtripInputs
        difftestRegResponseBytes =
      some () := by
  native_decide

/-- `move-lean-difftest` harness calls this with **no args**; we ignore them and run `execVerify…`. -/
def caRegistrationHelpersRoundtripNative : List MoveValue → Option (List MoveValue) :=
  fun _ =>
    match
      execVerifyRegistrationProof difftestRegistrationOracle difftestRegistrationRoundtripInputs
        difftestRegResponseBytes with
    | some _ => some [.bool true]
    | none => none

end AptosFormal.Move.Programs.RegistrationDifftestOracle
