#!/usr/bin/env bash
set -euo pipefail

#
# generate_msl_spec_template.sh
#
# Purpose: Generate Move Specification Language (MSL) spec template for a function.
# Creates skeleton with abort conditions, ensures clauses, and helper functions.
#
# Usage:
#   ./generate_msl_spec_template.sh --function <name> [OPTIONS]
#
# Options:
#   --function <name>    Function name (required): transfer_internal, withdraw_internal, etc.
#   --module <name>      Module name (optional, default: confidential_asset)
#   --entry-point        Generate spec for entry point function (includes signer handling)
#   --internal           Generate spec for internal function (default)
#   --output <file>      Output file (default: stdout)
#   --abort-codes <csv>  Comma-separated abort codes to include (e.g., "196612,65537,196613")
#   --state-updates      Include state update ensures clauses
#
# Examples:
#   ./generate_msl_spec_template.sh --function transfer_internal --state-updates
#   ./generate_msl_spec_template.sh --function transfer --entry-point --output transfer_spec.move
#   ./generate_msl_spec_template.sh --function withdraw_internal --abort-codes "196612,65537"
#

# Configuration
FUNCTION=""
MODULE="confidential_asset"
IS_ENTRY_POINT=false
OUTPUT_FILE=""
ABORT_CODES=""
STATE_UPDATES=false

# Common abort codes
declare -A ABORT_CODE_NAMES
ABORT_CODE_NAMES[196612]="ETOKEN_IS_FROZEN"
ABORT_CODE_NAMES[196609]="ETOKEN_STORE_NOT_PUBLISHED"
ABORT_CODE_NAMES[65537]="EPROOF_VERIFICATION_FAILED"
ABORT_CODE_NAMES[196613]="ERECIPIENT_REJECTED_TRANSFER"
ABORT_CODE_NAMES[65538]="EINSUFFICIENT_BALANCE"
ABORT_CODE_NAMES[65540]="EINVALID_PROOF_FORMAT"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --function)
      FUNCTION="$2"
      shift 2
      ;;
    --module)
      MODULE="$2"
      shift 2
      ;;
    --entry-point)
      IS_ENTRY_POINT=true
      shift
      ;;
    --internal)
      IS_ENTRY_POINT=false
      shift
      ;;
    --output)
      OUTPUT_FILE="$2"
      shift 2
      ;;
    --abort-codes)
      ABORT_CODES="$2"
      shift 2
      ;;
    --state-updates)
      STATE_UPDATES=true
      shift
      ;;
    --help)
      head -n 25 "$0" | tail -n +3 | sed 's/^# //' | sed 's/^#//'
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      echo "Run with --help for usage"
      exit 1
      ;;
  esac
done

# Validate arguments
if [[ -z "$FUNCTION" ]]; then
  echo -e "${RED}Error: --function is required${NC}"
  echo "Run with --help for usage"
  exit 1
fi

# Generate spec template
generate_spec() {
  local output=""

  # Header comment
  output+="/-!\n"
  output+="# MSL Specification for ${FUNCTION}\n"
  output+="\n"
  output+="Generated by generate_msl_spec_template.sh\n"
  output+="\n"
  output+="TODO: Review and customize this template:\n"
  output+="  1. Fill in missing abort conditions based on function logic\n"
  output+="  2. Add ensures clauses for state updates\n"
  output+="  3. Define helper spec functions if needed\n"
  output+="  4. Verify abort order matches implementation order\n"
  output+="-/\n"
  output+="\n"

  # Spec block opening
  output+="spec ${FUNCTION}(\n"

  # Generate parameters based on function type
  if [[ "$IS_ENTRY_POINT" == true ]]; then
    output+="    sender: &signer,\n"
    output+="    // TODO: Add remaining parameters\n"
  else
    output+="    // TODO: Add parameters (e.g., store: &mut ConfidentialAssetStore, proof: &Proof)\n"
  fi

  output+=") {\n"

  # Pragma for strict abort checking
  output+="    pragma aborts_if_is_strict;\n"
  output+="\n"

  # Entry point specific abort conditions
  if [[ "$IS_ENTRY_POINT" == true ]]; then
    output+="    let sender_addr = signer::address_of(sender);\n"
    output+="\n"
    output+="    // Abort if store doesn't exist\n"
    output+="    aborts_if !exists<ConfidentialAssetStore>(sender_addr) \n"
    output+="        with ${ABORT_CODE_NAMES[196609]:-ETOKEN_STORE_NOT_PUBLISHED};\n"
    output+="\n"
    output+="    // Delegate remaining conditions to internal function spec\n"
  fi

  # Parse abort codes and generate abort_if clauses
  if [[ -n "$ABORT_CODES" ]]; then
    IFS=',' read -ra CODES <<< "$ABORT_CODES"
    output+="    // Abort conditions (order matches implementation)\n"
    for code in "${CODES[@]}"; do
      local code_name="${ABORT_CODE_NAMES[$code]:-EUNKNOWN_ERROR_$code}"
      output+="    aborts_if /* TODO: condition */ with ${code_name};\n"
    done
    output+="\n"
  else
    output+="    // TODO: Add abort conditions\n"
    output+="    // Common patterns:\n"
    output+="    //   aborts_if store.frozen with ETOKEN_IS_FROZEN;\n"
    output+="    //   aborts_if !verify_proof(proof) with EPROOF_VERIFICATION_FAILED;\n"
    output+="    //   aborts_if balance < amount with EINSUFFICIENT_BALANCE;\n"
    output+="\n"
  fi

  # State update ensures clauses
  if [[ "$STATE_UPDATES" == true ]]; then
    output+="    // State updates\n"
    output+="    // TODO: Add ensures clauses for state changes\n"
    output+="    // Common patterns:\n"
    output+="    //   ensures store.field == new_value;\n"
    output+="    //   ensures len(store.pending_balance) == len(old(store.pending_balance)) + 1;\n"
    output+="\n"
    output+="    // Balance conservation\n"
    output+="    // TODO: Add balance sum preservation if applicable\n"
    output+="    // let old_sum = sum_balance_chunks(old(store.pending_balance));\n"
    output+="    // let new_sum = sum_balance_chunks(store.pending_balance);\n"
    output+="    // ensures old_sum == new_sum; // or old_sum + delta == new_sum\n"
    output+="\n"
    output+="    // Frame conditions\n"
    output+="    // TODO: Add ensures for fields that should NOT change\n"
    output+="    // ensures store.frozen == old(store.frozen);\n"
    output+="    // ensures store.incoming_allow_list == old(store.incoming_allow_list);\n"
    output+="\n"
  fi

  output+="}\n"

  # Helper spec functions section
  output+="\n"
  output+="spec module {\n"
  output+="    // TODO: Define helper spec functions if needed\n"
  output+="    \n"
  output+="    /// Sum of encrypted balance chunks (symbolic interpretation)\n"
  output+="    /// Axiomatized because we cannot decrypt without keys\n"
  output+="    fun sum_balance_chunks(chunks: vector<TwistedElGamalCiphertext>): u64;\n"
  output+="\n"
  output+="    /// Axiom: sum is additive\n"
  output+="    axiom forall chunks1: vector<TwistedElGamalCiphertext>, \n"
  output+="                 chunks2: vector<TwistedElGamalCiphertext>:\n"
  output+="        sum_balance_chunks(concat(chunks1, chunks2)) == \n"
  output+="        sum_balance_chunks(chunks1) + sum_balance_chunks(chunks2);\n"
  output+="\n"
  output+="    /// Axiom: empty sum is zero\n"
  output+="    axiom sum_balance_chunks(empty_vector<TwistedElGamalCiphertext>()) == 0;\n"
  output+="\n"
  output+="    // TODO: Add operation-specific helper functions\n"
  output+="    // Examples:\n"
  output+="    //   fun extract_amount(proof: &Proof): u64;\n"
  output+="    //   fun verify_proof(proof: &Proof): bool;\n"
  output+="}\n"

  echo -e "$output"
}

# Output to file or stdout
if [[ -n "$OUTPUT_FILE" ]]; then
  generate_spec > "$OUTPUT_FILE"
  echo -e "${GREEN}✅ MSL spec template generated!${NC}" >&2
  echo "" >&2
  echo "Output file: $OUTPUT_FILE" >&2
  echo "" >&2
  echo -e "${YELLOW}Next steps:${NC}" >&2
  echo "  1. Review the generated spec and fill in TODOs" >&2
  echo "  2. Copy spec into .spec.move file next to implementation" >&2
  echo "  3. Test compilation: cd aptos-experimental && aptos move prove --filter ${FUNCTION}" >&2
  echo "" >&2
  echo -e "${BLUE}Tip: See MSL_SPEC_PATTERN_LIBRARY.md for common spec patterns${NC}" >&2
else
  generate_spec
fi
