#!/usr/bin/env bash
# scripts/generate_pc_range_lemmas.sh — Generate PC-range sub-lemma scaffolds
#
# Purpose: Automates the boilerplate for Workaround 1 (split into sub-lemmas) from
#          ELABORATOR_PERFORMANCE_WORKAROUNDS.md. Generates skeleton Lean files with
#          PC-range composition theorems to avoid elaborator O(N²) bottleneck.
#
# Usage:
#   ./scripts/generate_pc_range_lemmas.sh --operation normalization --pcs 14 --chunk-size 7
#   ./scripts/generate_pc_range_lemmas.sh --operation transfer --pcs 24 --chunk-size 8
#   ./scripts/generate_pc_range_lemmas.sh --help
#
# Output:
#   - Lean file with sub-lemma skeletons
#   - Composition theorem scaffold
#   - @[irreducible] state definitions
#
# Example output for normalization (14 PCs, chunk-size 7):
#   @[irreducible] def normalizationState0 : CallFrame := ...
#   @[irreducible] def normalizationState7 : CallFrame := ...
#   @[irreducible] def normalizationState14 : CallFrame := ...
#
#   theorem normalization_pcs_0_6 : ... := by sorry
#   theorem normalization_pcs_7_13 : ... := by sorry
#   theorem normalization_eval_equiv_functional_sim : ... := by
#     have h1 := normalization_pcs_0_6 ...
#     have h2 := normalization_pcs_7_13 ...
#     exact run_chain h1 h2

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Defaults
OPERATION=""
TOTAL_PCS=0
CHUNK_SIZE=10
OUTPUT_FILE=""
DRY_RUN=false

usage() {
    cat <<EOF
Usage: $0 --operation <name> --pcs <count> [OPTIONS]

Required:
  --operation <name>    Operation name (normalization, withdrawal, transfer, rotation, registration)
  --pcs <count>         Total number of PCs to cover

Options:
  --chunk-size <n>      PCs per sub-lemma (default: 10, recommended: 7-10)
  --output <file>       Output file (default: PCRangeComposition_<Operation>.lean)
  --dry-run             Print output to stdout instead of file
  -h, --help            Show this help

Examples:
  # Normalization (14 PCs → 2 sub-lemmas of 7 PCs each)
  $0 --operation normalization --pcs 14 --chunk-size 7

  # Transfer (24 PCs → 3 sub-lemmas of 8 PCs each)
  $0 --operation transfer --pcs 24 --chunk-size 8

  # Registration singleton branch (50 PCs → 5 sub-lemmas of 10 PCs each)
  $0 --operation registration_singleton --pcs 50

Output:
  Generates Lean file with:
    - @[irreducible] state definitions (one per chunk boundary)
    - Sub-lemma theorem scaffolds (one per chunk)
    - Final composition theorem (chains sub-lemmas via run_chain)

Note:
  This script generates SCAFFOLDS only (theorems have 'sorry' placeholders).
  You must fill in:
    1. State definitions (replace '...' with actual CallFrame expressions)
    2. Proof bodies (replace 'sorry' with actual PC-step chains)
EOF
}

# Parse args
while [ $# -gt 0 ]; do
    case "$1" in
        --operation)
            OPERATION="$2"
            shift 2
            ;;
        --pcs)
            TOTAL_PCS="$2"
            shift 2
            ;;
        --chunk-size)
            CHUNK_SIZE="$2"
            shift 2
            ;;
        --output)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo -e "${RED}ERROR: Unknown argument '$1'${NC}" >&2
            usage >&2
            exit 1
            ;;
    esac
done

# Validate required args
if [ -z "$OPERATION" ]; then
    echo -e "${RED}ERROR: --operation required${NC}" >&2
    usage >&2
    exit 1
fi

if [ "$TOTAL_PCS" -le 0 ]; then
    echo -e "${RED}ERROR: --pcs must be > 0${NC}" >&2
    exit 1
fi

# Derive capitalized operation name (for module name)
OP_CAP="$(echo "${OPERATION}" | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')"
OP_LOWER="$(echo "${OPERATION}" | tr '[:upper:]' '[:lower:]')"

# Default output file
if [ -z "$OUTPUT_FILE" ]; then
    OUTPUT_FILE="PCRangeComposition_${OP_CAP}.lean"
fi

# Calculate number of chunks
NUM_CHUNKS=$(( (TOTAL_PCS + CHUNK_SIZE - 1) / CHUNK_SIZE ))

echo -e "${BLUE}PC Range Lemma Generator${NC}"
echo "Operation: $OPERATION"
echo "Total PCs: $TOTAL_PCS"
echo "Chunk size: $CHUNK_SIZE"
echo "Number of sub-lemmas: $NUM_CHUNKS"
echo "Output: $OUTPUT_FILE"
echo ""

# Generate Lean file content
generate_lean_content() {
    local op="$1"
    local op_cap="$2"
    local total_pcs="$3"
    local chunk_size="$4"
    local num_chunks="$5"

    cat <<EOF
-- PCRangeComposition_${op_cap}.lean
-- Auto-generated by scripts/generate_pc_range_lemmas.sh
-- Purpose: PC-range sub-lemmas for ${op_cap} to avoid elaborator O(N²) bottleneck
-- See: ELABORATOR_PERFORMANCE_WORKAROUNDS.md (Workaround 1)

import MovementFormal.Experimental.ConfidentialAsset.${op_cap}.EvalEquiv
import MovementFormal.MoveModel.StepLemmas.Run

namespace MovementFormal.Experimental.ConfidentialAsset.${op_cap}

open MoveModel

-- ============================================================================
-- Intermediate States (chunk boundaries)
-- ============================================================================
-- Note: Replace '...' with actual CallFrame expressions from your proof context.

EOF

    # Generate @[irreducible] state definitions
    for (( i=0; i<=num_chunks; i++ )); do
        local pc=$(( i * chunk_size ))
        if [ "$pc" -gt "$total_pcs" ]; then
            pc=$total_pcs
        fi
        cat <<EOF
@[irreducible]
def ${op}State${pc} : CallFrame :=
  -- TODO: Replace with actual state at PC ${pc}
  -- Example: { initialFrame with pc := ${pc}, locals := ... }
  sorry

EOF
    done

    cat <<EOF
-- ============================================================================
-- Sub-Lemma Scaffolds (one per chunk)
-- ============================================================================

EOF

    # Generate sub-lemma theorems
    for (( i=0; i<num_chunks; i++ )); do
        local start_pc=$(( i * chunk_size ))
        local end_pc=$(( (i + 1) * chunk_size - 1 ))
        if [ "$end_pc" -ge "$total_pcs" ]; then
            end_pc=$(( total_pcs - 1 ))
        fi
        local fuel=$(( end_pc - start_pc + 1 ))
        local next_state_pc=$(( end_pc + 1 ))
        if [ "$next_state_pc" -gt "$total_pcs" ]; then
            next_state_pc=$total_pcs
        fi

        cat <<EOF
-- PCs ${start_pc}-${end_pc} (${fuel} steps)
theorem ${op}_pcs_${start_pc}_${end_pc}
    (env : ModuleEnvironment)
    (cs : ControlStack)
    (stack : List Value)
    (ms : MachineState)
    -- Add additional hypotheses as needed (locals, refs, etc.)
    : MoveModel.run env ${op}State${start_pc} cs stack ms ${fuel} =
        .success ${op}State${next_state_pc} cs stack ms := by
  -- TODO: Chain step_pc${start_pc} through step_pc${end_pc}
  -- Example:
  --   have h${start_pc} := step_pc${start_pc} env ${op}State${start_pc} ...
  --   have h$((start_pc + 1)) := step_pc$((start_pc + 1)) env ...
  --   ...
  --   exact run_chain [h${start_pc}, h$((start_pc + 1)), ...]
  sorry

EOF
    done

    cat <<EOF
-- ============================================================================
-- Final Composition Theorem (chains all sub-lemmas)
-- ============================================================================

theorem ${op}_eval_equiv_functional_sim
    (env : ModuleEnvironment)
    (initialFrame : CallFrame)
    (cs : ControlStack)
    (stack : List Value)
    (ms : MachineState)
    (h_pc : initialFrame.pc = 0)
    -- Add operation-specific hypotheses here
    : MoveModel.run env ${op}State0 cs stack ms ${total_pcs} =
        .success ${op}State${total_pcs} cs stack ms := by
  -- Chain all sub-lemmas
EOF

    for (( i=0; i<num_chunks; i++ )); do
        local start_pc=$(( i * chunk_size ))
        local end_pc=$(( (i + 1) * chunk_size - 1 ))
        if [ "$end_pc" -ge "$total_pcs" ]; then
            end_pc=$(( total_pcs - 1 ))
        fi
        echo "  have h${i} := ${op}_pcs_${start_pc}_${end_pc} env cs stack ms"
    done

    cat <<EOF
  -- TODO: Use run_chain or run_trans to combine h0, h1, ..., h$((num_chunks - 1))
  -- Example:
  --   exact run_chain [h0, h1, h2, ...]
  sorry

end MovementFormal.Experimental.ConfidentialAsset.${op_cap}

-- ============================================================================
-- Appendix: Helper Lemmas (if not already in StepLemmas.Run)
-- ============================================================================

namespace MoveModel

-- Chain two run steps
theorem run_trans {fuel1 fuel2 : Nat}
    {env : ModuleEnvironment}
    {frame1 frame2 frame3 : CallFrame}
    {cs1 cs2 cs3 : ControlStack}
    {stack1 stack2 stack3 : List Value}
    {ms1 ms2 ms3 : MachineState}
    (h1 : run env frame1 cs1 stack1 ms1 fuel1 = .success frame2 cs2 stack2 ms2)
    (h2 : run env frame2 cs2 stack2 ms2 fuel2 = .success frame3 cs3 stack3 ms3)
    : run env frame1 cs1 stack1 ms1 (fuel1 + fuel2) = .success frame3 cs3 stack3 ms3 := by
  sorry  -- TODO: Prove using run_add_fuel lemma

-- Chain list of run steps
-- def run_chain : List (run ...) → run ... := List.foldl run_trans
-- (Recursive definition TBD based on actual MoveModel.run signature)

end MoveModel
EOF
}

# Generate content
CONTENT=$(generate_lean_content "$OP_LOWER" "$OP_CAP" "$TOTAL_PCS" "$CHUNK_SIZE" "$NUM_CHUNKS")

# Output
if [ "$DRY_RUN" = true ]; then
    echo -e "${YELLOW}[DRY RUN] Generated content:${NC}"
    echo ""
    echo "$CONTENT"
else
    echo "$CONTENT" > "$OUTPUT_FILE"
    echo -e "${GREEN}✅ Generated: $OUTPUT_FILE${NC}"
    echo ""
    echo "Next steps:"
    echo "  1. Review generated file: $OUTPUT_FILE"
    echo "  2. Fill in state definitions (replace 'sorry' in ${OP_LOWER}State* defs)"
    echo "  3. Fill in sub-lemma proofs (chain step_pc* lemmas)"
    echo "  4. Implement run_chain/run_trans helpers (or import from StepLemmas.Run)"
    echo "  5. Test build: lake build MovementFormal.Experimental.ConfidentialAsset.${OP_CAP}.PCRangeComposition"
    echo ""
    echo "Estimated effort per sub-lemma: ~1-2 days (for $CHUNK_SIZE PCs)"
    echo "Total sub-lemmas: $NUM_CHUNKS"
    echo "Estimated total: ~$((NUM_CHUNKS * 2)) days (serial)"
fi

exit 0
