#!/usr/bin/env bash
# scripts/publish_docker_image.sh — Docker image build and publish automation
#
# Phase 7 deliverable (plan §10.4). Automates the build-publish-digest-capture workflow
# for the CA formal-verification reproducibility Docker image.
#
# Usage:
#   ./scripts/publish_docker_image.sh [--build-only|--publish-only|--skip-tests]
#   ./scripts/publish_docker_image.sh --help
#
# Modes:
#   --build-only   : Build image locally, skip publish
#   --publish-only : Publish existing image (assumes already built)
#   --skip-tests   : Skip post-build verification tests
#   (default)      : Build + test + publish + capture digest
#
# Environment variables:
#   DOCKER_REGISTRY : Target registry (default: ghcr.io)
#   DOCKER_ORG      : Organization/user (default: movement-labs)
#   DOCKER_REPO     : Repository name (default: ca-formal-verification)
#   DOCKER_TAG      : Tag (default: auto-generated from date)
#   GITHUB_TOKEN    : Required for ghcr.io publish (GitHub PAT with packages:write)
#
# Exit codes:
#   0 = Success (image built and/or published)
#   1 = Build/publish failure
#   2 = Usage error or missing prerequisites

set -euo pipefail

FORMAL_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO_ROOT="$(cd "$FORMAL_ROOT/../../.." && pwd)"
cd "$REPO_ROOT"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
DOCKER_REGISTRY="${DOCKER_REGISTRY:-ghcr.io}"
DOCKER_ORG="${DOCKER_ORG:-movement-labs}"
DOCKER_REPO="${DOCKER_REPO:-ca-formal-verification}"
DOCKER_TAG="${DOCKER_TAG:-$(date +%Y-%m-%d)}"
DOCKER_LATEST_TAG="${DOCKER_LATEST_TAG:-latest}"
IMAGE_NAME="${DOCKER_REGISTRY}/${DOCKER_ORG}/${DOCKER_REPO}"
DOCKERFILE="aptos-move/framework/formal/audit/Dockerfile"
TOOLCHAIN_LOCK="aptos-move/framework/formal/audit/toolchain.lock"

# Mode flags
BUILD_ONLY=false
PUBLISH_ONLY=false
SKIP_TESTS=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --build-only)
            BUILD_ONLY=true
            shift
            ;;
        --publish-only)
            PUBLISH_ONLY=true
            shift
            ;;
        --skip-tests)
            SKIP_TESTS=true
            shift
            ;;
        --help)
            echo "Usage: $0 [--build-only|--publish-only|--skip-tests]"
            echo ""
            echo "Modes:"
            echo "  --build-only    Build image locally, skip publish"
            echo "  --publish-only  Publish existing image (assumes already built)"
            echo "  --skip-tests    Skip post-build verification tests"
            echo "  (default)       Build + test + publish + capture digest"
            echo ""
            echo "Environment variables:"
            echo "  DOCKER_REGISTRY : Target registry (default: ghcr.io)"
            echo "  DOCKER_ORG      : Organization/user (default: movement-labs)"
            echo "  DOCKER_REPO     : Repository name (default: ca-formal-verification)"
            echo "  DOCKER_TAG      : Tag (default: $(date +%Y-%m-%d))"
            echo "  GITHUB_TOKEN    : Required for ghcr.io publish"
            exit 0
            ;;
        *)
            echo -e "${RED}Error:${NC} Unknown option: $1"
            echo "Run with --help for usage"
            exit 2
            ;;
    esac
done

# Prerequisites check
check_prerequisites() {
    echo -e "${BLUE}Checking prerequisites...${NC}"

    if ! command -v docker &> /dev/null; then
        echo -e "${RED}Error:${NC} Docker not installed"
        echo "Install: https://docs.docker.com/get-docker/"
        exit 2
    fi

    if [ ! -f "$DOCKERFILE" ]; then
        echo -e "${RED}Error:${NC} Dockerfile not found at $DOCKERFILE"
        exit 2
    fi

    if [ ! -f "$TOOLCHAIN_LOCK" ]; then
        echo -e "${YELLOW}Warning:${NC} toolchain.lock not found at $TOOLCHAIN_LOCK"
        echo "Creating minimal toolchain.lock..."
        mkdir -p "$(dirname "$TOOLCHAIN_LOCK")"
        cat > "$TOOLCHAIN_LOCK" <<EOF
# CA Formal Verification Toolchain Lock File
# Auto-generated by publish_docker_image.sh on $(date +%Y-%m-%d)

lean_version = "v4.24.0"
lake_version = "5.0.0-src+797c613"
z3_version = "4.11.2"
boogie_version = "3.5.1"
cvc5_version = "0.0.3"
rust_version = "1.86.0"
base_os = "ubuntu:22.04"
platform = "linux/amd64"

# Docker image digest (updated after publish)
# docker_image_digest = "sha256:..."
EOF
    fi

    if [ "$PUBLISH_ONLY" = false ] && ! docker info &> /dev/null; then
        echo -e "${RED}Error:${NC} Docker daemon not running"
        exit 2
    fi

    if [ "$BUILD_ONLY" = false ] && [ -z "${GITHUB_TOKEN:-}" ]; then
        echo -e "${YELLOW}Warning:${NC} GITHUB_TOKEN not set"
        echo "Publishing to $DOCKER_REGISTRY requires authentication"
        echo "Set GITHUB_TOKEN to a GitHub PAT with packages:write scope"
        echo ""
        echo "Continuing with build-only mode..."
        BUILD_ONLY=true
    fi

    echo -e "${GREEN}✓${NC} Prerequisites OK"
}

# Build Docker image
build_image() {
    if [ "$PUBLISH_ONLY" = true ]; then
        echo -e "${BLUE}Skipping build (--publish-only)${NC}"
        return
    fi

    echo ""
    echo -e "${BLUE}=====================================${NC}"
    echo -e "${BLUE}Building Docker Image${NC}"
    echo -e "${BLUE}=====================================${NC}"
    echo "  Image: $IMAGE_NAME:$DOCKER_TAG"
    echo "  Dockerfile: $DOCKERFILE"
    echo "  Build context: $REPO_ROOT"
    echo ""

    local build_start=$(date +%s)

    # Build with progress output
    docker build \
        --platform linux/amd64 \
        -t "$IMAGE_NAME:$DOCKER_TAG" \
        -t "$IMAGE_NAME:$DOCKER_LATEST_TAG" \
        -f "$DOCKERFILE" \
        --progress=plain \
        . || {
        echo -e "${RED}✗ Build failed${NC}"
        exit 1
    }

    local build_end=$(date +%s)
    local build_duration=$((build_end - build_start))

    echo ""
    echo -e "${GREEN}✓ Build complete${NC} (${build_duration}s)"

    # Show image info
    local image_size=$(docker images "$IMAGE_NAME:$DOCKER_TAG" --format "{{.Size}}")
    echo "  Image size: $image_size"
    echo "  Tags:"
    echo "    - $IMAGE_NAME:$DOCKER_TAG"
    echo "    - $IMAGE_NAME:$DOCKER_LATEST_TAG"
}

# Test Docker image
test_image() {
    if [ "$SKIP_TESTS" = true ]; then
        echo -e "${BLUE}Skipping tests (--skip-tests)${NC}"
        return
    fi

    if [ "$PUBLISH_ONLY" = true ]; then
        echo -e "${BLUE}Skipping tests (--publish-only)${NC}"
        return
    fi

    echo ""
    echo -e "${BLUE}=====================================${NC}"
    echo -e "${BLUE}Testing Docker Image${NC}"
    echo -e "${BLUE}=====================================${NC}"
    echo ""

    # Test 1: Toolchain versions
    echo -e "${BLUE}Test 1:${NC} Verifying toolchain versions..."
    docker run --rm "$IMAGE_NAME:$DOCKER_TAG" bash -c '
        echo "Lean: $(lean --version | head -1)"
        echo "Lake: $(lake --version)"
        echo "Z3: $(${Z3_EXE} --version | head -1)"
        echo "Boogie: $(${BOOGIE_EXE} -version 2>&1 | head -1)"
        echo "Movement: $(movement --version 2>&1 | head -1 || echo "movement CLI present")"
    ' || {
        echo -e "${RED}✗ Toolchain verification failed${NC}"
        exit 1
    }
    echo -e "${GREEN}✓ Toolchain OK${NC}"
    echo ""

    # Test 2: Lean build smoke test
    echo -e "${BLUE}Test 2:${NC} Lean build smoke test..."
    docker run --rm "$IMAGE_NAME:$DOCKER_TAG" bash -c '
        cd aptos-move/framework/formal/lean
        lake build MovementFormal.Std.Hash.Sha3_256 > /dev/null 2>&1
    ' || {
        echo -e "${RED}✗ Lean build failed${NC}"
        exit 1
    }
    echo -e "${GREEN}✓ Lean build OK${NC}"
    echo ""

    # Test 3: verify-ca.sh exists and is executable
    echo -e "${BLUE}Test 3:${NC} verify-ca.sh availability..."
    docker run --rm "$IMAGE_NAME:$DOCKER_TAG" test -x ./audit/verify-ca.sh || {
        echo -e "${RED}✗ verify-ca.sh not found or not executable${NC}"
        exit 1
    }
    echo -e "${GREEN}✓ verify-ca.sh OK${NC}"
    echo ""

    echo -e "${GREEN}✓ All tests passed${NC}"
}

# Publish Docker image
publish_image() {
    if [ "$BUILD_ONLY" = true ]; then
        echo -e "${BLUE}Skipping publish (--build-only)${NC}"
        return
    fi

    echo ""
    echo -e "${BLUE}=====================================${NC}"
    echo -e "${BLUE}Publishing Docker Image${NC}"
    echo -e "${BLUE}=====================================${NC}"
    echo "  Registry: $DOCKER_REGISTRY"
    echo "  Image: $IMAGE_NAME:$DOCKER_TAG"
    echo ""

    # Login to registry
    echo -e "${BLUE}Authenticating to $DOCKER_REGISTRY...${NC}"
    echo "$GITHUB_TOKEN" | docker login "$DOCKER_REGISTRY" -u "$DOCKER_ORG" --password-stdin || {
        echo -e "${RED}✗ Authentication failed${NC}"
        exit 1
    }
    echo -e "${GREEN}✓ Authenticated${NC}"
    echo ""

    # Push both tags
    echo -e "${BLUE}Pushing $IMAGE_NAME:$DOCKER_TAG...${NC}"
    docker push "$IMAGE_NAME:$DOCKER_TAG" || {
        echo -e "${RED}✗ Push failed${NC}"
        exit 1
    }
    echo -e "${GREEN}✓ Pushed $DOCKER_TAG${NC}"
    echo ""

    echo -e "${BLUE}Pushing $IMAGE_NAME:$DOCKER_LATEST_TAG...${NC}"
    docker push "$IMAGE_NAME:$DOCKER_LATEST_TAG" || {
        echo -e "${RED}✗ Push failed${NC}"
        exit 1
    }
    echo -e "${GREEN}✓ Pushed $DOCKER_LATEST_TAG${NC}"
}

# Capture digest and update toolchain.lock
capture_digest() {
    if [ "$BUILD_ONLY" = true ]; then
        echo -e "${BLUE}Skipping digest capture (--build-only)${NC}"
        return
    fi

    echo ""
    echo -e "${BLUE}=====================================${NC}"
    echo -e "${BLUE}Capturing Digest${NC}"
    echo -e "${BLUE}=====================================${NC}"
    echo ""

    # Get digest from local image
    local digest=$(docker inspect "$IMAGE_NAME:$DOCKER_TAG" | jq -r '.[0].RepoDigests[0]' 2>/dev/null || echo "")

    if [ -z "$digest" ] || [ "$digest" = "null" ]; then
        echo -e "${YELLOW}Warning:${NC} Could not capture digest from local image"
        echo "Digest will be available after publish completes and image is pulled"
        return
    fi

    echo "  Digest: $digest"
    echo ""

    # Update toolchain.lock
    if [ -f "$TOOLCHAIN_LOCK" ]; then
        echo -e "${BLUE}Updating $TOOLCHAIN_LOCK...${NC}"

        # Add or update docker_image_digest line
        if grep -q "^docker_image_digest" "$TOOLCHAIN_LOCK"; then
            # Update existing line
            sed -i.bak "s|^docker_image_digest.*|docker_image_digest = \"$digest\"|" "$TOOLCHAIN_LOCK"
            rm "${TOOLCHAIN_LOCK}.bak"
        else
            # Append new line
            echo "" >> "$TOOLCHAIN_LOCK"
            echo "# Docker image digest (captured on $(date +%Y-%m-%d))" >> "$TOOLCHAIN_LOCK"
            echo "docker_image_digest = \"$digest\"" >> "$TOOLCHAIN_LOCK"
        fi

        echo -e "${GREEN}✓ toolchain.lock updated${NC}"
    fi
}

# Summary
print_summary() {
    echo ""
    echo -e "${BLUE}=====================================${NC}"
    echo -e "${BLUE}Summary${NC}"
    echo -e "${BLUE}=====================================${NC}"
    echo ""

    if [ "$PUBLISH_ONLY" = false ]; then
        echo -e "${GREEN}✓ Image built${NC}"
        echo "    $IMAGE_NAME:$DOCKER_TAG"
        echo "    $IMAGE_NAME:$DOCKER_LATEST_TAG"
        echo ""
    fi

    if [ "$BUILD_ONLY" = false ]; then
        echo -e "${GREEN}✓ Image published${NC}"
        echo "    Pull: docker pull $IMAGE_NAME:$DOCKER_TAG"
        echo "    Run:  docker run --rm $IMAGE_NAME:$DOCKER_TAG"
        echo ""
    fi

    if [ "$BUILD_ONLY" = true ]; then
        echo "Next steps:"
        echo "  1. Test: docker run --rm $IMAGE_NAME:$DOCKER_TAG ./audit/verify-ca.sh --op register"
        echo "  2. Publish: $0 --publish-only"
    fi

    echo ""
    echo -e "${GREEN}Done!${NC}"
}

# Main
main() {
    check_prerequisites
    build_image
    test_image
    publish_image
    capture_digest
    print_summary
}

main "$@"
