#!/usr/bin/env bash
# scripts/setup_git_hooks.sh — Install git hooks for CA formal verification
#
# Purpose: Set up pre-commit and pre-push hooks to catch issues early
# Hooks: Lean build check, axiom drift check, sorry detection, documentation consistency
#
# Usage:
#   ./scripts/setup_git_hooks.sh install    # Install hooks
#   ./scripts/setup_git_hooks.sh uninstall  # Remove hooks
#   ./scripts/setup_git_hooks.sh status     # Check hook status

set -euo pipefail

FORMAL_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO_ROOT="$(cd "$FORMAL_ROOT/../../.." && pwd)"
GIT_DIR="$REPO_ROOT/.git"
HOOKS_DIR="$GIT_DIR/hooks"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

usage() {
    cat <<EOF
Usage: $0 <command>

Commands:
  install     Install git hooks for CA formal verification
  uninstall   Remove installed hooks
  status      Check which hooks are installed

Hooks installed:
  pre-commit  - Fast checks before commit (~30s)
                • Lean syntax check
                • No sorry in committed files
                • Axiom drift check
                • Documentation consistency

  pre-push    - Comprehensive checks before push (~5 min)
                • Full Lean build
                • verify-ca.sh quick mode
                • Trust boundary reconciliation

Examples:
  $0 install      # Set up hooks
  $0 status       # Check current state
  $0 uninstall    # Remove hooks
EOF
}

# ============================================================================
# Pre-Commit Hook Content
# ============================================================================

generate_pre_commit_hook() {
    cat <<'HOOK_EOF'
#!/usr/bin/env bash
# Pre-commit hook for CA formal verification
# Auto-generated by scripts/setup_git_hooks.sh

set -euo pipefail

FORMAL_ROOT="$(git rev-parse --show-toplevel)/aptos-move/framework/formal"
cd "$FORMAL_ROOT"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  CA Formal Verification Pre-Commit Checks                 ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check 1: No sorry in staged .lean files
echo -e "${BLUE}[1/4] Checking for sorry in staged Lean files...${NC}"
if git diff --cached --name-only | grep '\.lean$' > /dev/null; then
    if git diff --cached | grep '^+.*sorry' | grep -v '^+.*--.*sorry' > /dev/null; then
        echo -e "${RED}❌ FAIL: Found 'sorry' in staged Lean files${NC}"
        echo ""
        echo "Sorry locations:"
        git diff --cached | grep -n '^+.*sorry' | grep -v '^+.*--.*sorry'
        echo ""
        echo "Remove sorry before committing or use --no-verify to skip this check."
        exit 1
    fi
fi
echo -e "${GREEN}✅ PASS${NC}"

# Check 2: Axiom drift check
echo ""
echo -e "${BLUE}[2/4] Checking axiom drift...${NC}"
if ! ./scripts/track_axiom_drift.sh --alert 28 > /dev/null 2>&1; then
    echo -e "${YELLOW}⚠️  WARNING: Axiom count may exceed threshold${NC}"
    echo "Review with: ./scripts/check_axioms.sh"
    echo ""
    # Warning only, don't block commit
fi
echo -e "${GREEN}✅ PASS${NC}"

# Check 3: Lean syntax check (quick)
echo ""
echo -e "${BLUE}[3/4] Lean syntax check (staged files)...${NC}"
if git diff --cached --name-only | grep '\.lean$' > /dev/null; then
    cd lean
    for file in $(git diff --cached --name-only | grep '\.lean$'); do
        if ! lake env lean --run "$file" > /dev/null 2>&1; then
            echo -e "${RED}❌ FAIL: Syntax error in $file${NC}"
            echo "Fix syntax errors before committing."
            exit 1
        fi
    done
    cd "$FORMAL_ROOT"
fi
echo -e "${GREEN}✅ PASS${NC}"

# Check 4: Documentation consistency
echo ""
echo -e "${BLUE}[4/4] Documentation consistency...${NC}"
if git diff --cached --name-only | grep -E '(AXIOM_INVENTORY|TRUST_BOUNDARIES)\.md$' > /dev/null; then
    echo -e "${YELLOW}⚠️  NOTE: Trust boundary docs modified${NC}"
    echo "Ensure reconciliation script passes: ./scripts/reconcile_trust_boundaries.sh"
fi
echo -e "${GREEN}✅ PASS${NC}"

echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  Pre-commit checks passed!                                 ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
HOOK_EOF
}

# ============================================================================
# Pre-Push Hook Content
# ============================================================================

generate_pre_push_hook() {
    cat <<'HOOK_EOF'
#!/usr/bin/env bash
# Pre-push hook for CA formal verification
# Auto-generated by scripts/setup_git_hooks.sh

set -euo pipefail

FORMAL_ROOT="$(git rev-parse --show-toplevel)/aptos-move/framework/formal"
cd "$FORMAL_ROOT"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  CA Formal Verification Pre-Push Checks (~5 min)          ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check 1: Full Lean build
echo -e "${BLUE}[1/3] Full Lean build...${NC}"
cd lean
if ! lake build > /tmp/pre-push-lean-build.log 2>&1; then
    echo -e "${RED}❌ FAIL: Lean build failed${NC}"
    echo ""
    echo "Build errors:"
    tail -50 /tmp/pre-push-lean-build.log
    echo ""
    echo "Fix build errors before pushing or use --no-verify to skip."
    exit 1
fi
cd "$FORMAL_ROOT"
echo -e "${GREEN}✅ PASS${NC}"

# Check 2: verify-ca.sh quick mode
echo ""
echo -e "${BLUE}[2/3] Quick verification check...${NC}"
if ! ./scripts/run_comprehensive_validation.sh --quick > /tmp/pre-push-verify.log 2>&1; then
    echo -e "${RED}❌ FAIL: Verification checks failed${NC}"
    echo ""
    echo "Check output:"
    tail -50 /tmp/pre-push-verify.log
    echo ""
    echo "Fix verification issues before pushing."
    exit 1
fi
echo -e "${GREEN}✅ PASS${NC}"

# Check 3: Trust boundary reconciliation
echo ""
echo -e "${BLUE}[3/3] Trust boundary reconciliation...${NC}"
if [ -f scripts/reconcile_trust_boundaries.sh ]; then
    if ! bash scripts/reconcile_trust_boundaries.sh > /tmp/pre-push-trust.log 2>&1; then
        echo -e "${RED}❌ FAIL: Trust boundary reconciliation failed${NC}"
        echo ""
        cat /tmp/pre-push-trust.log
        echo ""
        echo "Update TRUST_BOUNDARIES.md or AXIOM_INVENTORY.md as needed."
        exit 1
    fi
fi
echo -e "${GREEN}✅ PASS${NC}"

echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  Pre-push checks passed! Safe to push.                    ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Cleanup
rm -f /tmp/pre-push-*.log
HOOK_EOF
}

# ============================================================================
# Commands
# ============================================================================

cmd_install() {
    echo -e "${BLUE}Installing CA formal verification git hooks...${NC}"
    echo ""

    # Ensure hooks directory exists
    mkdir -p "$HOOKS_DIR"

    # Install pre-commit hook
    echo -e "${BLUE}[1/2] Installing pre-commit hook...${NC}"
    generate_pre_commit_hook > "$HOOKS_DIR/pre-commit"
    chmod +x "$HOOKS_DIR/pre-commit"
    echo -e "${GREEN}✅ Installed: $HOOKS_DIR/pre-commit${NC}"

    # Install pre-push hook
    echo ""
    echo -e "${BLUE}[2/2] Installing pre-push hook...${NC}"
    generate_pre_push_hook > "$HOOKS_DIR/pre-push"
    chmod +x "$HOOKS_DIR/pre-push"
    echo -e "${GREEN}✅ Installed: $HOOKS_DIR/pre-push${NC}"

    echo ""
    echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║  Git hooks installed successfully!                        ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo "Hooks will run automatically on commit/push."
    echo "To bypass hooks (not recommended): git commit --no-verify"
    echo ""
    echo "Check hook status: $0 status"
}

cmd_uninstall() {
    echo -e "${YELLOW}Uninstalling CA formal verification git hooks...${NC}"
    echo ""

    removed=0

    if [ -f "$HOOKS_DIR/pre-commit" ]; then
        rm "$HOOKS_DIR/pre-commit"
        echo -e "${GREEN}✅ Removed: pre-commit hook${NC}"
        removed=$((removed + 1))
    fi

    if [ -f "$HOOKS_DIR/pre-push" ]; then
        rm "$HOOKS_DIR/pre-push"
        echo -e "${GREEN}✅ Removed: pre-push hook${NC}"
        removed=$((removed + 1))
    fi

    if [ "$removed" -eq 0 ]; then
        echo "No CA verification hooks found."
    else
        echo ""
        echo -e "${GREEN}Uninstalled $removed hook(s).${NC}"
    fi
}

cmd_status() {
    echo -e "${BLUE}CA Formal Verification Git Hooks Status${NC}"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""

    if [ -f "$HOOKS_DIR/pre-commit" ]; then
        echo -e "pre-commit:  ${GREEN}✅ Installed${NC}"
        echo "  Location: $HOOKS_DIR/pre-commit"
        echo "  Checks: sorry detection, axiom drift, Lean syntax, docs consistency"
    else
        echo -e "pre-commit:  ${RED}❌ Not installed${NC}"
    fi

    echo ""

    if [ -f "$HOOKS_DIR/pre-push" ]; then
        echo -e "pre-push:    ${GREEN}✅ Installed${NC}"
        echo "  Location: $HOOKS_DIR/pre-push"
        echo "  Checks: full Lean build, verify-ca.sh quick, trust boundaries"
    else
        echo -e "pre-push:    ${RED}❌ Not installed${NC}"
    fi

    echo ""

    if [ -f "$HOOKS_DIR/pre-commit" ] || [ -f "$HOOKS_DIR/pre-push" ]; then
        echo -e "${BLUE}To uninstall:${NC} $0 uninstall"
    else
        echo -e "${YELLOW}No hooks installed.${NC}"
        echo -e "${BLUE}To install:${NC} $0 install"
    fi
}

# ============================================================================
# Main
# ============================================================================

if [ $# -eq 0 ]; then
    usage
    exit 1
fi

case "$1" in
    install)
        cmd_install
        ;;
    uninstall)
        cmd_uninstall
        ;;
    status)
        cmd_status
        ;;
    --help|-h)
        usage
        ;;
    *)
        echo -e "${RED}ERROR: Unknown command '$1'${NC}" >&2
        echo ""
        usage >&2
        exit 1
        ;;
esac

exit 0
