import MovementFormal.MoveModel.Value
import MovementFormal.MoveModel.Native.Registration
import MovementFormal.MoveModel.Programs.Registration

namespace MovementFormal.MoveModel.Programs.RegistrationDifftestOracle
axiom stub : True
end MovementFormal.MoveModel.Programs.RegistrationDifftestOracle
