import MovementFormal.Experimental.ConfidentialAsset.Normalization.EvalEquiv

namespace MovementFormal.Experimental.ConfidentialAsset.Normalization.Composition
axiom stub : True
end MovementFormal.Experimental.ConfidentialAsset.Normalization.Composition
